#!/bin/sh

WANIF=`uci -P /var/state -q get network.wan.ifname`
WANUP=`uci -P /var/state -q get network.wan.up`
WAN2IF=`uci -P /var/state -q get network.wan2.ifname`
WAN2UP=`uci -P /var/state -q get network.wan2.up`
if [ -z "$WANUP" ]; then WANUP=0; fi
if [ -z "$WAN2UP" ]; then WAN2UP=0; fi
logger -t chilli "Chilli hotplug due to $ACTION of $INTERFACE ($DEVICE). WAN=${WANIF},${WANUP} WAN2=${WAN2IF},${WAN2UP}"

dorestart() {
    ## Disable DHCP on LAN
    logger -t chilli "Starting chilli on br-lan and setting dhcp.lan.ignore='1'"
    uci set dhcp.lan.ignore='1'
    uci commit dhcp
    /etc/init.d/dnsmasq restart

    # Now restart
    /etc/init.d/chilli restart
}

if [ "$ACTION" == "ifup" ]; then
    echo "ifup for $INTERFACE ($DEVICE)"
    if [ "$INTERFACE" == "wan" ]; then
        dorestart

    elif [ "$INTERFACE" == "wan2" ]; then
        if [ "$WANUP" == "1" ]; then
            dorestart
        else
            dorestart
        fi
    elif [ "$INTERFACE" == "lan" ]; then
        ## Enable DHCP on LAN
        logger -t chilli "Starting $INTERFACE, and setting dhcp.lan.ignore='0'"
        uci set dhcp.lan.ignore='0'
        uci commit dhcp
        /etc/init.d/dnsmasq restart

    else
        logger -t chilli "Not starting chilli, since $INTERFACE is not wan or wan2"
    fi

elif [ "$ACTION" == "ifdown" ]; then
    echo "ifdown for $INTERFACE ($DEVICE)"
    if [ "$INTERFACE" == "wan" ] || [ "$INTERFACE" == "wan2" ]; then
        if [ "$WANUP" == "1" ] || [ "$WAN2UP" == "1" ]; then
            if [ "$WANUP" == "1" ]; then
                logger -t chilli "WANUP=$WANUP"
            elif [ "$WAN2UP" == "1" ]; then
                logger -t chilli "WAN2UP=$WAN2UP"
            fi
            dorestart
        else
            ## Enable DHCP on LAN
            logger -t chilli "Since neither wan or wan2 up, setting dhcp.lan.ignore='0'"
            uci set dhcp.lan.ignore='0'
            uci commit dhcp
            /etc/init.d/dnsmasq restart

            /etc/init.d/chilli stop
            logger -t chilli "Neither wan or wan2 up. Stopping chilli."
        fi
    else
        logger -t chilli "$ACTION for $INTERFACE ($DEVICE). Chilli not changed."
    fi

else
    echo "$ACTION for $INTERFACE ($DEVICE)"
    logger -t chilli "Unknown: $ACTION for $INTERFACE ($DEVICE)"
fi