#!/bin/sh

CHILLINET=`uci get chilli.@chilli[0].net`
LANNET=192.168.1.1
USBNET=192.168.8.1
MASK=255.255.255.0
echo "iptables -I FORWARD -s ${CHILLINET} -d ${LANNET}/${MASK} -j REJECT"
echo "iptables -I FORWARD -s ${CHILLINET} -d ${USBNET}/${MASK} -j REJECT"

if [ "$ACTION" == "ifup" ]; then
    if [ "$INTERFACE" == "hotspotsystem" ]; then
        logger -t firewall "Firewall hotplug due to $ACTION of $INTERFACE ($DEVICE)."
        logger -t firewall "iptables -I FORWARD -s ${CHILLINET} -d ${LANNET}/${MASK} -j REJECT"
        logger -t firewall "iptables -I FORWARD -s ${CHILLINET} -d ${USBNET}/${MASK} -j REJECT"

        # Disabling LANNET
        #iptables -I FORWARD -s ${CHILLINET} -d ${LANNET}/${MASK} -j REJECT
        #iptables -I FORWARD -s ${CHILLINET} -d ${USBNET}/${MASK} -j REJECT
    fi

elif [ "$ACTION" == "ifdown" ]; then
    if [ "$INTERFACE" == "hotspotsystem" ]; then
        logger -t firewall "Firewall hotplug DOWN due to $ACTION of $INTERFACE ($DEVICE)."
        logger -t firewall "iptables -D FORWARD -s ${CHILLINET} -d ${LANNET}/${MASK} -j REJECT"
        logger -t firewall "iptables -D FORWARD -s ${CHILLINET} -d ${USBNET}/${MASK} -j REJECT"

        #iptables -D FORWARD -s ${CHILLINET} -d ${LANNET}/${MASK} -j REJECT
        #iptables -D FORWARD -s ${CHILLINET} -d ${USBNET}/${MASK} -j REJECT
    fi
fi